schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night # Default colors
    primary:
      background: "0x1a1b26"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "0x32344a"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x787c99"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"

  tokyo-night-storm: &tokyo-night-storm # Default colors
    primary:
      background: "0x24283b"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "0x32344a"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x9699a8"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"

  palenight: &palenight
    primary:
      background: "0x292d3e"
      foreground: "0x959dcb"

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: "0x292d3e"
      cursor: "0x959dcb"

    # Normal colors
    normal:
      black: "0x292d3e"
      red: "0xf07178"
      green: "0xc3e88d"
      yellow: "0xffcb6b"
      blue: "0x82aaff"
      magenta: "0xc792ea"
      cyan: "0x89ddff"
      white: "0x959dcb"

    # Bright colors
    bright:
      black: "0x676e95"
      red: "0xf07178"
      green: "0xc3e88d"
      yellow: "0xffcb6b"
      blue: "0x82aaff"
      magenta: "0xc792ea"
      cyan: "0x89ddff"
      white: "0xffffff"

    indexed_colors:
      - { index: 16, color: "0xf78c6c" }
      - { index: 17, color: "0xff5370" }
      - { index: 18, color: "0x444267" }
      - { index: 19, color: "0x32374d" }
      - { index: 20, color: "0x8796b0" }
      - { index: 21, color: "0x959dcb" }

  onedark-deep: &onedark-deep
    primary:
      background: "0x1a212e"
      foreground: "0x93a4c3"

    # Normal colors
    normal:
      black: "0x0c0e15"
      red: "0xf65866"
      green: "0x8bcd5b"
      yellow: "0xefbd5d"
      blue: "0x41a7fc"
      magenta: "0xc75ae8"
      cyan: "0x34bfd0"
      white: "0x93a4c3"

colors: *onedark-deep
font:
  size: 13.0
  normal:
    family: UbuntuMono Nerd Font
  bold:
    family: UbuntuMono Nerd Font
window:
  decorations: none
  padding:
    x: 0
    y: 0
