[colors.normal]
black = "#5C5F77"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[colors.primary]
background = "#EFF1F5"
bright_foreground = "#4C4F69"
dim_foreground = "#4C4F69"
foreground = "#4C4F69"

[colors.cursor]
cursor = "#DC8A78"
text = "#EFF1F5"

[colors.selection]
background = "#8aadf4"
text = "#EFF1F5"

[colors.vi_mode_cursor]
cursor = "#7288FD"
text = "#EFF1F5"

[font]
size = 12.0

[font.normal]
family = "Monaspace Neon"
