[colors.normal]
black = "#5C5F77"
blue = "#4285F4"
cyan = "#179299"
green = "#0F9D58"
magenta = "#C71C56"
red = "#DB4437"
white = "#ACB0BE"
yellow = "#F4B400"

[colors.primary]
background = "#EFF1F5"
bright_foreground = "#4C4F69"
dim_foreground = "#4C4F69"
foreground = "#4C4F69"

[colors.cursor]
cursor = "#4285F4"
text = "#EFF1F5"

[colors.selection]
background = "#e6e9ef"
text = "#EFF1F5"

[colors.vi_mode_cursor]
cursor = "#4285F4"
text = "#EFF1F5"

[cursor]
thickness = 0.2

[font]
size = 11.0

[font.normal]
family = "Monaspace Neon"
