[colors.normal]
black = "#0D0B10"
blue = "#40739A"
cyan = "#3B8187"
green = "#59795F"
magenta = "#9E6253"
red = "#9D4B53"
white = "#D1D3CC"
yellow = "#A78A58"

[colors.primary]
background = "#E1E4DC"
bright_foreground = "#2E2C2F"
dim_foreground = "#2E2C2F"
foreground = "#2E2C2F"

[colors.cursor]
cursor = "#516E56"
text = "#E1E4DC"

[colors.selection]
background = "#D1D3CC"
text = "#3E3D3F"

[colors.vi_mode_cursor]
cursor = "#516E56"
text = "#E1E4DC"

[cursor]
thickness = 0.2

[font]
size = 11.0

[font.normal]
family = "Monaspace Neon"
