schemes:
  light: &light
    primary:
      background: "0xe1e2e7"
      foreground: "0x414868"
    normal:
      black: "0x252525"
      red: "0xf44747"
      green: "0x6a9955"
      yellow: "0xfea736"
      blue: "0x569cd6"
      magenta: "0xd16d9e"
      cyan: "0x4ec9b0"
      white: "0xd4d4d4"
colors: *light
font:
  size: 11.0
  normal:
    family: JetBrains Mono Nerd Font
  bold:
    family: JetBrains Mono Nerd Font
window:
  decorations: none
  padding:
    x: 0
    y: 0
