schemes:
  darkplus: &darkplus
    primary:
      background: "0x131921"
      foreground: "0xd4d4d4"
    normal:
      black: "0x252525"
      red: "0xf44747"
      green: "0x6a9955"
      yellow: "0xfebd69"
      blue: "0x569cd6"
      magenta: "0xd16d9e"
      cyan: "0x4ec9b0"
      white: "0xd4d4d4"

colors: *darkplus
font:
  size: 13.0
  normal:
    family: UbuntuMono Nerd Font
  bold:
    family: UbuntuMono Nerd Font
window:
  decorations: none
  padding:
    x: 0
    y: 0
