#!/bin/bash
# options to be displayed
lock="lock"
logout="logout"
suspend="suspend"
reboot="reboot"
shutdown="shutdown"
# options passed into variable
options="$lock\n$logout\n$suspend\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | rofi -dmenu -no-fixed-num-lines -p "")"
case $chosen in
$lock)
  swaylock -d -c 131921 --font-size 40px --indicator-radius 200 --indicator-thickness 5
  ;;
$logout)
  systemctl exit
  ;;
$suspend)
  systemctl suspend
  ;;
$reboot)
  systemctl reboot
  ;;
$shutdown)
  systemctl poweroff
  ;;
esac
