#!/bin/bash

cmd=$1
dest=${2:-"e+1"}

active=$(hyprctl activeworkspace -j | jq ".id")
activewindows=$(hyprctl activeworkspace -j | jq ".windows")
last=$(hyprctl workspaces -j | jq ".[-1].id")

[ $dest == "e+1" ] &&
  [ $active == $last ] &&
  [ $activewindows != "0" ] &&
  dest=$(($last + 1))

hyprctl dispatch $cmd $dest
