local ok1, onedarkpro = pcall(require, "onedarkpro")
if not ok1 then
  return
end

onedarkpro.setup {
  -- dark_theme = "onedark_dark",
  colors = {
    onedark = {
      bg = "#131921",
    },
    onedark_vivid = {
      bg = "#131921",
    },
    onedark_dark = {
      bg = "#131921",
    },
  },
  highlights = {
    --syntax
    Comment = { fg = "#6e6f70", style = "italic" },
    Constant = { fg = "#5ae0df" },
    String = { fg = "#66ffbf" },
    Character = { fg = "#66ffbf" },
    Number = { fg = "#3ddbd9" },
    Boolean = { fg = "#3ddbd9" },
    Float = { fg = "#3ddbd9" },
    Identifier = { fg = "#33b1ff" },
    Function = { fg = "#00b4cc" },
    Statement = { fg = "#be95ff" },
    Conditional = { fg = "#c8a5ff" },
    Repeat = { fg = "#c8a5ff" },
    Label = { fg = "#c8a5ff" },
    Operator = { fg = "#ff669c" },
    Keyword = { fg = "#ff669c" },
    Exception = { fg = "#ff669c" },
    PreProc = { fg = "#ff91c1" },
    Include = { fg = "#ff91c1" },
    Define = { fg = "#ff91c1" },
    Macro = { fg = "#ff91c1" },
    PreCondit = { fg = "#ff91c1" },
    Type = { fg = "#08bdba" },
    StorageClass = { fg = "#08bdba" },
    Structure = { fg = "#08bdba" },
    Typedef = { fg = "#08bdba" },
    Special = { fg = "#8cb6ff" },
    SpecialChar = { fg = "#8cb6ff" },
    Delimiter = { fg = "#8cb6ff" },
    SpecialComment = { fg = "#8cb6ff" },
    Error = { fg = "#ee5396" },
    Todo = { fg = "#000000", bg = "yellow" },

    -- treesitter
    ["@annotation"] = { fg = "#ff91c1", style = "italic" },
    ["@attribute"] = { fg = "#5ae0df" },
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@comment"] = { link = "Comment" },
    ["@conditional"] = { link = "Conditional" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = "#5ae0df" },
    ["@constant.macro"] = { link = "@constant" },
    ["@constructor"] = { fg = "#be95ff" },
    ["@error"] = { fg = "#ee5396" },
    ["@exception"] = { link = "Keyword" },
    ["@field"] = { fg = "#78a9ff" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = "#99f3ff", style = "italic" },
    ["@function.macro"] = { fg = "#ee5396" },
    ["@include"] = { link = "Include" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = "#ff7039", style = "bold" },
    ["@keyword.operator"] = { fg = "#b6b8bb", style = "bold" },
    ["@keyword.return"] = { link = "@keyword" },
    ["@label"] = { link = "Conditional" },
    ["@method"] = { link = "Function" },
    ["@namespace"] = { fg = "#52bdff" },
    ["@number"] = { link = "Number" },
    ["@operator"] = { fg = "#b6b8bb", style = "bold" },
    ["@parameter"] = { link = "Identifier" },
    ["@parameter.reference"] = { link = "@parameter" },
    ["@property"] = { fg = "#78a9ff" },
    ["@punctuation.delimiter"] = { fg = "#b6b8bb" },
    ["@punctuation.bracket"] = { fg = "#b6b8bb" },
    ["@punctuation.special"] = { fg = "#b6b8bb" },
    ["@repeat"] = { link = "Repeat" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { fg = "#2dc7c4" },
    ["@string.escape"] = { fg = "#2dc7c4", style = "bold" },
    ["@string.special"] = { link = "Special" },
    ["@symbol"] = { link = "Identifier" },
    ["@tag"] = { link = "Special" },
    ["@tag.attribute"] = { link = "Constant" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@text"] = {},
    ["@text.strong"] = { link = "Bold" },
    ["@text.underline"] = { link = "Underlined" },
    ["@text.strike"] = { style = "strikethrough" },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { style = "bold", fg = "#33b1ff" },
    ["@text.math"] = { link = "Special" },
    ["@text.reference"] = { fg = "#be95ff" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.note"] = { fg = "#78a9ff" },
    ["@text.warning"] = { fg = "#be95ff" },
    ["@text.danger"] = { fg = "#ee5396" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = "#ffc69d", style = "italic" },
    ["@variable"] = { fg = "#ffb966" },
    ["@variable.builtin"] = { fg = "#ee5396" },

    -- plugin
    NvimTreeNormal = {
      fg = "#BBBBBB",
      bg = "#1c2531",
    },
    TelescopeNormal = {
      fg = "${fg}",
      bg = "${bg}",
    },
  },
}

local colorscheme = "onedarkpro"
local ok2, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
if not ok2 then
  return
end
