# zero.nvim — Light
# https://github.com/your-username/zero.nvim

[colors]
foreground    = "#242731"
background    = "#f4f5f7"
cursor_bg     = "#0c8045"
cursor_border = "#0c8045"
cursor_fg     = "#f4f5f7"
selection_bg  = "#c5e3d0"
selection_fg  = "#242731"

ansi = [
  "#d8dce3",
  "#d61f3a",
  "#0c8045",
  "#7d6a00",
  "#1d6fd0",
  "#7138df",
  "#0b766c",
  "#636b78",
]

brights = [
  "#9ba2ad",
  "#bf1731",
  "#0b713b",
  "#6d5c00",
  "#1a61b9",
  "#602cc7",
  "#096960",
  "#242731",
]

[colors.tab_bar]
background = "#e8eaee"

[colors.tab_bar.active_tab]
bg_color  = "#f4f5f7"
fg_color  = "#0c8045"

[colors.tab_bar.inactive_tab]
bg_color  = "#e8eaee"
fg_color  = "#636b78"

[colors.tab_bar.inactive_tab_hover]
bg_color  = "#fbfcfd"
fg_color  = "#242731"

[colors.tab_bar.new_tab]
bg_color  = "#e8eaee"
fg_color  = "#9ba2ad"

[colors.tab_bar.new_tab_hover]
bg_color  = "#fbfcfd"
fg_color  = "#0c8045"
